language: shell
services:
- docker
env:
  global:
  - BASE_REPO=$DOCKER_USER/${TRAVIS_REPO_SLUG##*/}
  - DOCKER_TAG=${TRAVIS_COMMIT:0:7}
  - DEV_REPO=${BASE_REPO}:$DOCKER_TAG
  - RELEASE_REPO=${BASE_REPO}:$TRAVIS_TAG
  - LATEST_REPO=${BASE_REPO}:latest
  - secure: BsZX+tPBFrtA2r4sbsdUJGhLQSEs7PENI6DvhtI30+BZIBG04myijzuEbEbQc2t6crmI+8Fd5aybwIDZeGi4ZPixB4KDyMqp5xxtLyQ0LXk39v5UPOAqvfErDmtVambxlHe/4PSZ2ilW01IF5Js3PU+V461KAKkCXC679ClMYjtlYfNDF5Q/aR5fKwH1fAzLPwcylOIrfFITQpT7UUz415691koSgrvAGZgPdxbIcB83PF6xBFHEGJn1eSflJuHL33l1F+rPx+nBshqgOYhyhk3HPAlxRWYgD5gxInTid9p7KjnZ0iAaf50i/a71vyLzQ89/aykbPMS9KFLEXRFGkoCa+bKR6vO1U3c+gr3VMsGxd6Za0nvB65aCgY2b/QZNoyX36dhOzWU/NcLg6sHH/zCgEMGtvxbY1Vsiogox419LP3o9Vcu6g+m75FKjPua5i20QNKLOzn4HGMmECNdZFqLQOQQ6OYx6E1K2yxS41uN9BmmFgMVjtIAYuPhyowQhkjz5uNxeiFuQS+a9Du/P2HEzY9Faxckkh4V29bvxFq+1IkEBwb7QlB39XqJccs+vMWEpP0LY0GE9ryA1jR5baOpAcus3G7ayhympaJ4rGlUXoSyST8sUK3jiNg7PLfIZsMVmqOWehBuh/Fn+KUQFbG4G1UJZT6sMJrGPJk6c1AA=
  - secure: GBtM2nLbd88B2jKnFU0vE4mBehOTD208uIBaJT1GeHwq8gw1m81X8AyQ056dXHjhtXN/177cazURYZAHAvcNMD3ecY8jrQwENlPQgAsAeVBup4BwDcRLKyhSjiDQd32+LDc9KFbVOZfhwilZ7I6Oi3LUtfnXaKy4gwt65DLFcXIr6N2KVKQmK6G+9K0B5m0VvKZ+m68D198RjrlAXscPcVdYRvnkOub7B9v6t9qW1Z7V3ebR+CRrBLrI4+jY7ZRAlChaehCx4XDBTKt2BrF7m9N0J3cMn/X5Xv9RLIR44vm+dW9dZ39VK1drwLjJitD41ZIUcZY8zSFxbijfmVTvAP8yTWfxjAd0xBWU4lYb2N0vWdsZQZ/W3R2sN9yllv4evZxIjGaP7Z3o7tjwI7ewX7VyIVVCXboLTmCPVp8Yy3HZgt3jB91qxpMWLv7BkJWrAIZVtNzjtkzYOPU3tTnalgwrppx1Z7GtaXRotV+HPx/i9ck4WltBhDHWVRuZqfHiYJx6DnCJFBXcdHONhKVn+tdpy8HReukXv802pc9eNWoK7tDHemaItrYNI3+EKFmcZL7veujTOselQWM4zz3eupPniBfDEw+60NfOKKyp662dg9Svacm0LqIaCJaloRTWkRX4wla3SMTa7/Ck9ggo2/hKukGkueEfhuTaAYuQrmM=
before_install:
- env
- docker login -u$DOCKER_USER -p$DOCKER_PASS
install:
- if [[ -z "$TRAVIS_TAG" ]]; then docker build nginx -t $DEV_REPO && docker push $DEV_REPO;
  fi
- if [[ -n "$TRAVIS_TAG" ]]; then docker pull $DEV_REPO && docker tag $DEV_REPO $RELEASE_REPO
  && docker tag $DEV_REPO $LATEST_REPO && docker push $RELEASE_REPO && docker push
  $LATEST_REPO; fi
