#!/bin/bash -e

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-blademainer}
GRPC_VERSION=${GRPC_VERSION:-1.23}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-1.23}
BUILD_VERSION=${BUILD_VERSION:-1}
DEV_VERSION=${DEV_VERSION:-1}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}
BUILDS=("protoc-all" "protoc" "prototool" "grpc-cli" "gen-grpc-gateway")
RELEASE=${RELEASE:-false}
GCC_VERSION=${GCC_VERSION:-7.4.0}
